// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RecursosHumanos.Api.Data;

#nullable disable

namespace RecursosHumanos.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260604143014_AddMovimientosPersonal")]
    partial class AddMovimientosPersonal
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RecursosHumanos.Api.Models.Asignacion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Cargo")
                        .HasColumnType("text")
                        .HasColumnName("cargo");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly?>("Desde")
                        .HasColumnType("date")
                        .HasColumnName("desde");

                    b.Property<DateOnly?>("Hasta")
                        .HasColumnType("date")
                        .HasColumnName("hasta");

                    b.Property<Guid>("InstitucionId")
                        .HasColumnType("uuid")
                        .HasColumnName("institucion_id");

                    b.Property<Guid>("PersonalId")
                        .HasColumnType("uuid")
                        .HasColumnName("personal_id");

                    b.Property<string>("Unidad")
                        .HasColumnType("text")
                        .HasColumnName("unidad");

                    b.HasKey("Id");

                    b.HasIndex("InstitucionId");

                    b.HasIndex("PersonalId");

                    b.ToTable("asignaciones");
                });

            modelBuilder.Entity("RecursosHumanos.Api.Models.Baja", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly?>("FechaBaja")
                        .HasColumnType("date")
                        .HasColumnName("fecha_baja");

                    b.Property<string>("Motivo")
                        .HasColumnType("text")
                        .HasColumnName("motivo");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text")
                        .HasColumnName("observaciones");

                    b.Property<Guid>("PersonalId")
                        .HasColumnType("uuid")
                        .HasColumnName("personal_id");

                    b.HasKey("Id");

                    b.HasIndex("PersonalId");

                    b.ToTable("bajas");
                });

            modelBuilder.Entity("RecursosHumanos.Api.Models.ContactoEmergencia", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Apellidos")
                        .HasColumnType("text")
                        .HasColumnName("apellidos");

                    b.Property<string>("Celular")
                        .HasColumnType("text")
                        .HasColumnName("celular");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Direccion")
                        .HasColumnType("text")
                        .HasColumnName("direccion");

                    b.Property<string>("Nombres")
                        .HasColumnType("text")
                        .HasColumnName("nombres");

                    b.Property<Guid>("PersonalId")
                        .HasColumnType("uuid")
                        .HasColumnName("personal_id");

                    b.Property<string>("Telefono")
                        .HasColumnType("text")
                        .HasColumnName("telefono");

                    b.HasKey("Id");

                    b.HasIndex("PersonalId");

                    b.ToTable("contactos_emergencia");
                });

            modelBuilder.Entity("RecursosHumanos.Api.Models.Dependiente", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Apellidos")
                        .HasColumnType("text")
                        .HasColumnName("apellidos");

                    b.Property<string>("Celular")
                        .HasColumnType("text")
                        .HasColumnName("celular");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Direccion")
                        .HasColumnType("text")
                        .HasColumnName("direccion");

                    b.Property<string>("Nombres")
                        .HasColumnType("text")
                        .HasColumnName("nombres");

                    b.Property<Guid>("PersonalId")
                        .HasColumnType("uuid")
                        .HasColumnName("personal_id");

                    b.Property<string>("Tipo")
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.HasIndex("PersonalId");

                    b.ToTable("dependientes");
                });

            modelBuilder.Entity("RecursosHumanos.Api.Models.Destino", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CargoActual")
                        .HasColumnType("text")
                        .HasColumnName("cargo_actual");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EstadoPersonal")
                        .HasColumnType("text")
                        .HasColumnName("estado_personal");

                    b.Property<DateOnly?>("FechaDestino")
                        .HasColumnType("date")
                        .HasColumnName("fecha_destino");

                    b.Property<string>("MemoNro")
                        .HasColumnType("text")
                        .HasColumnName("memo_nro");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text")
                        .HasColumnName("observaciones");

                    b.Property<Guid>("PersonalId")
                        .HasColumnType("uuid")
                        .HasColumnName("personal_id");

                    b.Property<string>("UnidadActual")
                        .HasColumnType("text")
                        .HasColumnName("unidad_actual");

                    b.Property<string>("UnidadAnterior")
                        .HasColumnType("text")
                        .HasColumnName("unidad_anterior");

                    b.HasKey("Id");

                    b.HasIndex("PersonalId");

                    b.ToTable("destinos");
                });

            modelBuilder.Entity("RecursosHumanos.Api.Models.Especialidad", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Nombre")
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<string>("Tipo")
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.ToTable("especialidades");
                });

            modelBuilder.Entity("RecursosHumanos.Api.Models.Grado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<int>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.HasKey("Id");

                    b.ToTable("grados");
                });

            modelBuilder.Entity("RecursosHumanos.Api.Models.InfoPersonal", b =>
                {
                    b.Property<Guid>("PersonalId")
                        .HasColumnType("uuid")
                        .HasColumnName("personal_id");

                    b.Property<string>("Direccion")
                        .HasColumnType("text")
                        .HasColumnName("direccion");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("EstadoCivil")
                        .HasColumnType("text")
                        .HasColumnName("estado_civil");

                    b.Property<DateOnly?>("FechaIngreso")
                        .HasColumnType("date")
                        .HasColumnName("f_ingreso");

                    b.Property<DateOnly?>("FechaNacimiento")
                        .HasColumnType("date")
                        .HasColumnName("f_nac");

                    b.Property<string>("GrupoSanguineo")
                        .HasColumnType("text")
                        .HasColumnName("grupo_sanguineo");

                    b.Property<string>("Sigep")
                        .HasColumnType("text")
                        .HasColumnName("sigep");

                    b.Property<string>("TelCel")
                        .HasColumnType("text")
                        .HasColumnName("tel_cel");

                    b.Property<string>("TelPart")
                        .HasColumnType("text")
                        .HasColumnName("tel_part");

                    b.Property<string>("Zona")
                        .HasColumnType("text")
                        .HasColumnName("zona");

                    b.HasKey("PersonalId");

                    b.ToTable("info_personal");
                });

            modelBuilder.Entity("RecursosHumanos.Api.Models.Institucion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Nombre")
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<string>("Sigla")
                        .HasColumnType("text")
                        .HasColumnName("sigla");

                    b.Property<string>("Tipo")
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.ToTable("instituciones");
                });

            modelBuilder.Entity("RecursosHumanos.Api.Models.Personal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("AlturaCm")
                        .HasColumnType("numeric")
                        .HasColumnName("altura_cm");

                    b.Property<string>("ApEsposo")
                        .HasColumnType("text")
                        .HasColumnName("ap_esposo");

                    b.Property<string>("ApMaterno")
                        .HasColumnType("text")
                        .HasColumnName("ap_materno");

                    b.Property<string>("ApPaterno")
                        .HasColumnType("text")
                        .HasColumnName("ap_paterno");

                    b.Property<string>("Ci")
                        .HasColumnType("text")
                        .HasColumnName("ci");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Escalafon")
                        .HasColumnType("text")
                        .HasColumnName("escalafon");

                    b.Property<string>("Exp")
                        .HasColumnType("text")
                        .HasColumnName("exp");

                    b.Property<string>("FotoUrl")
                        .HasColumnType("text")
                        .HasColumnName("foto_url");

                    b.Property<string>("Genero")
                        .HasColumnType("text")
                        .HasColumnName("genero");

                    b.Property<int?>("GradoId")
                        .HasColumnType("integer")
                        .HasColumnName("grado_id");

                    b.Property<decimal?>("PesoKg")
                        .HasColumnType("numeric")
                        .HasColumnName("peso_kg");

                    b.Property<string>("PrimerNombre")
                        .HasColumnType("text")
                        .HasColumnName("primer_nombre");

                    b.Property<string>("SegundoNombre")
                        .HasColumnType("text")
                        .HasColumnName("segundo_nombre");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("GradoId");

                    b.ToTable("personal");
                });

            modelBuilder.Entity("RecursosHumanos.Api.Models.PersonalEspecialidad", b =>
                {
                    b.Property<Guid>("PersonalId")
                        .HasColumnType("uuid")
                        .HasColumnName("personal_id");

                    b.Property<Guid>("EspecialidadId")
                        .HasColumnType("uuid")
                        .HasColumnName("especialidad_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("PersonalId", "EspecialidadId");

                    b.HasIndex("EspecialidadId");

                    b.ToTable("personal_especialidad");
                });

            modelBuilder.Entity("RecursosHumanos.Api.Models.Reclamacion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly?>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<string>("NroMemorandum")
                        .HasColumnType("text")
                        .HasColumnName("nro_memorandum");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text")
                        .HasColumnName("observaciones");

                    b.Property<Guid>("PersonalId")
                        .HasColumnType("uuid")
                        .HasColumnName("personal_id");

                    b.Property<string>("Tipo")
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.Property<string>("UnidadRepresentada")
                        .HasColumnType("text")
                        .HasColumnName("unidad_representada");

                    b.HasKey("Id");

                    b.HasIndex("PersonalId");

                    b.ToTable("reclamaciones");
                });

            modelBuilder.Entity("RecursosHumanos.Api.Models.Rol", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("roles");
                });

            modelBuilder.Entity("RecursosHumanos.Api.Models.Situacion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Causal")
                        .HasColumnType("text")
                        .HasColumnName("causal");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly?>("FechaInicio")
                        .HasColumnType("date")
                        .HasColumnName("fecha_inicio");

                    b.Property<DateOnly?>("FechaRetorno")
                        .HasColumnType("date")
                        .HasColumnName("fecha_retorno");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text")
                        .HasColumnName("observaciones");

                    b.Property<Guid>("PersonalId")
                        .HasColumnType("uuid")
                        .HasColumnName("personal_id");

                    b.Property<string>("SituacionActual")
                        .HasColumnType("text")
                        .HasColumnName("situacion_actual");

                    b.Property<string>("Tipo")
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.HasIndex("PersonalId");

                    b.ToTable("situaciones");
                });

            modelBuilder.Entity("RecursosHumanos.Api.Models.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Username")
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.ToTable("usuarios");
                });

            modelBuilder.Entity("RecursosHumanos.Api.Models.UsuarioRol", b =>
                {
                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<Guid>("RolId")
                        .HasColumnType("uuid")
                        .HasColumnName("rol_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("UsuarioId", "RolId");

                    b.HasIndex("RolId");

                    b.ToTable("usuario_rol");
                });

            modelBuilder.Entity("RecursosHumanos.Api.Models.Asignacion", b =>
                {
                    b.HasOne("RecursosHumanos.Api.Models.Institucion", "Institucion")
                        .WithMany("Asignaciones")
                        .HasForeignKey("InstitucionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecursosHumanos.Api.Models.Personal", "Personal")
                        .WithMany("Asignaciones")
                        .HasForeignKey("PersonalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Institucion");

                    b.Navigation("Personal");
                });

            modelBuilder.Entity("RecursosHumanos.Api.Models.Baja", b =>
                {
                    b.HasOne("RecursosHumanos.Api.Models.Personal", "Personal")
                        .WithMany("Bajas")
                        .HasForeignKey("PersonalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personal");
                });

            modelBuilder.Entity("RecursosHumanos.Api.Models.ContactoEmergencia", b =>
                {
                    b.HasOne("RecursosHumanos.Api.Models.Personal", "Personal")
                        .WithMany("ContactosEmergencia")
                        .HasForeignKey("PersonalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personal");
                });

            modelBuilder.Entity("RecursosHumanos.Api.Models.Dependiente", b =>
                {
                    b.HasOne("RecursosHumanos.Api.Models.Personal", "Personal")
                        .WithMany("Dependientes")
                        .HasForeignKey("PersonalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personal");
                });

            modelBuilder.Entity("RecursosHumanos.Api.Models.Destino", b =>
                {
                    b.HasOne("RecursosHumanos.Api.Models.Personal", "Personal")
                        .WithMany("Destinos")
                        .HasForeignKey("PersonalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personal");
                });

            modelBuilder.Entity("RecursosHumanos.Api.Models.InfoPersonal", b =>
                {
                    b.HasOne("RecursosHumanos.Api.Models.Personal", "Personal")
                        .WithOne("InfoPersonal")
                        .HasForeignKey("RecursosHumanos.Api.Models.InfoPersonal", "PersonalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personal");
                });

            modelBuilder.Entity("RecursosHumanos.Api.Models.Personal", b =>
                {
                    b.HasOne("RecursosHumanos.Api.Models.Grado", "Grado")
                        .WithMany("Personal")
                        .HasForeignKey("GradoId");

                    b.Navigation("Grado");
                });

            modelBuilder.Entity("RecursosHumanos.Api.Models.PersonalEspecialidad", b =>
                {
                    b.HasOne("RecursosHumanos.Api.Models.Especialidad", "Especialidad")
                        .WithMany("PersonalEspecialidades")
                        .HasForeignKey("EspecialidadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecursosHumanos.Api.Models.Personal", "Personal")
                        .WithMany("PersonalEspecialidades")
                        .HasForeignKey("PersonalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Especialidad");

                    b.Navigation("Personal");
                });

            modelBuilder.Entity("RecursosHumanos.Api.Models.Reclamacion", b =>
                {
                    b.HasOne("RecursosHumanos.Api.Models.Personal", "Personal")
                        .WithMany("Reclamaciones")
                        .HasForeignKey("PersonalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personal");
                });

            modelBuilder.Entity("RecursosHumanos.Api.Models.Situacion", b =>
                {
                    b.HasOne("RecursosHumanos.Api.Models.Personal", "Personal")
                        .WithMany("Situaciones")
                        .HasForeignKey("PersonalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personal");
                });

            modelBuilder.Entity("RecursosHumanos.Api.Models.UsuarioRol", b =>
                {
                    b.HasOne("RecursosHumanos.Api.Models.Rol", "Rol")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecursosHumanos.Api.Models.Usuario", "Usuario")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("RecursosHumanos.Api.Models.Especialidad", b =>
                {
                    b.Navigation("PersonalEspecialidades");
                });

            modelBuilder.Entity("RecursosHumanos.Api.Models.Grado", b =>
                {
                    b.Navigation("Personal");
                });

            modelBuilder.Entity("RecursosHumanos.Api.Models.Institucion", b =>
                {
                    b.Navigation("Asignaciones");
                });

            modelBuilder.Entity("RecursosHumanos.Api.Models.Personal", b =>
                {
                    b.Navigation("Asignaciones");

                    b.Navigation("Bajas");

                    b.Navigation("ContactosEmergencia");

                    b.Navigation("Dependientes");

                    b.Navigation("Destinos");

                    b.Navigation("InfoPersonal");

                    b.Navigation("PersonalEspecialidades");

                    b.Navigation("Reclamaciones");

                    b.Navigation("Situaciones");
                });

            modelBuilder.Entity("RecursosHumanos.Api.Models.Rol", b =>
                {
                    b.Navigation("UsuarioRoles");
                });

            modelBuilder.Entity("RecursosHumanos.Api.Models.Usuario", b =>
                {
                    b.Navigation("UsuarioRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
