// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RecursosHumanos.Api.Data;

#nullable disable

namespace RecursosHumanos.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260604144142_AddDocumentosAuditoria")]
    partial class AddDocumentosAuditoria
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RecursosHumanos.Api.Models.Adjunto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Filename")
                        .HasColumnType("text")
                        .HasColumnName("filename");

                    b.Property<string>("Mime")
                        .HasColumnType("text")
                        .HasColumnName("mime");

                    b.Property<int?>("Size")
                        .HasColumnType("integer")
                        .HasColumnName("size");

                    b.Property<string>("Url")
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.ToTable("adjuntos");
                });

            modelBuilder.Entity("RecursosHumanos.Api.Models.Archivo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Codigo")
                        .HasColumnType("text")
                        .HasColumnName("codigo");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly?>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<DateOnly?>("Fin")
                        .HasColumnType("date")
                        .HasColumnName("fin");

                    b.Property<DateOnly?>("Inicio")
                        .HasColumnType("date")
                        .HasColumnName("inicio");

                    b.Property<string>("Nombre")
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<string>("Tipo")
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.ToTable("archivos");
                });

            modelBuilder.Entity("RecursosHumanos.Api.Models.ArchivoRel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ArchivoId")
                        .HasColumnType("bigint")
                        .HasColumnName("archivo_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EntityId")
                        .HasColumnType("text")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .HasColumnType("text")
                        .HasColumnName("entity_type");

                    b.HasKey("Id");

                    b.HasIndex("ArchivoId");

                    b.ToTable("archivos_rel");
                });

            modelBuilder.Entity("RecursosHumanos.Api.Models.Asignacion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Cargo")
                        .HasColumnType("text")
                        .HasColumnName("cargo");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly?>("Desde")
                        .HasColumnType("date")
                        .HasColumnName("desde");

                    b.Property<DateOnly?>("Hasta")
                        .HasColumnType("date")
                        .HasColumnName("hasta");

                    b.Property<Guid>("InstitucionId")
                        .HasColumnType("uuid")
                        .HasColumnName("institucion_id");

                    b.Property<Guid>("PersonalId")
                        .HasColumnType("uuid")
                        .HasColumnName("personal_id");

                    b.Property<string>("Unidad")
                        .HasColumnType("text")
                        .HasColumnName("unidad");

                    b.HasKey("Id");

                    b.HasIndex("InstitucionId");

                    b.HasIndex("PersonalId");

                    b.ToTable("asignaciones");
                });

            modelBuilder.Entity("RecursosHumanos.Api.Models.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Accion")
                        .HasColumnType("text")
                        .HasColumnName("accion");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Entidad")
                        .HasColumnType("text")
                        .HasColumnName("entidad");

                    b.Property<string>("EntidadId")
                        .HasColumnType("text")
                        .HasColumnName("entidad_id");

                    b.Property<string>("Payload")
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.HasKey("Id");

                    b.HasIndex("ActorId");

                    b.ToTable("audit_logs");
                });

            modelBuilder.Entity("RecursosHumanos.Api.Models.Baja", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly?>("FechaBaja")
                        .HasColumnType("date")
                        .HasColumnName("fecha_baja");

                    b.Property<string>("Motivo")
                        .HasColumnType("text")
                        .HasColumnName("motivo");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text")
                        .HasColumnName("observaciones");

                    b.Property<Guid>("PersonalId")
                        .HasColumnType("uuid")
                        .HasColumnName("personal_id");

                    b.HasKey("Id");

                    b.HasIndex("PersonalId");

                    b.ToTable("bajas");
                });

            modelBuilder.Entity("RecursosHumanos.Api.Models.BajaMedica", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly?>("Desde")
                        .HasColumnType("date")
                        .HasColumnName("desde");

                    b.Property<DateOnly?>("Hasta")
                        .HasColumnType("date")
                        .HasColumnName("hasta");

                    b.Property<string>("InstitucionMedica")
                        .HasColumnType("text")
                        .HasColumnName("institucion_medica");

                    b.Property<string>("Nro")
                        .HasColumnType("text")
                        .HasColumnName("nro");

                    b.Property<string>("NroFolio")
                        .HasColumnType("text")
                        .HasColumnName("nro_folio");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text")
                        .HasColumnName("observaciones");

                    b.Property<Guid>("PersonalId")
                        .HasColumnType("uuid")
                        .HasColumnName("personal_id");

                    b.HasKey("Id");

                    b.HasIndex("PersonalId");

                    b.ToTable("bajas_medicas");
                });

            modelBuilder.Entity("RecursosHumanos.Api.Models.Comision", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AutoridadFirma")
                        .HasColumnType("text")
                        .HasColumnName("autoridad_firma");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly?>("Desde")
                        .HasColumnType("date")
                        .HasColumnName("desde");

                    b.Property<DateOnly?>("Hasta")
                        .HasColumnType("date")
                        .HasColumnName("hasta");

                    b.Property<string>("Nro")
                        .HasColumnType("text")
                        .HasColumnName("nro");

                    b.Property<string>("NroFolio")
                        .HasColumnType("text")
                        .HasColumnName("nro_folio");

                    b.Property<string>("NroMemo")
                        .HasColumnType("text")
                        .HasColumnName("nro_memo");

                    b.Property<Guid>("PersonalId")
                        .HasColumnType("uuid")
                        .HasColumnName("personal_id");

                    b.Property<string>("UnidadOrg")
                        .HasColumnType("text")
                        .HasColumnName("unidad_org");

                    b.HasKey("Id");

                    b.HasIndex("PersonalId");

                    b.ToTable("comisiones");
                });

            modelBuilder.Entity("RecursosHumanos.Api.Models.ContactoEmergencia", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Apellidos")
                        .HasColumnType("text")
                        .HasColumnName("apellidos");

                    b.Property<string>("Celular")
                        .HasColumnType("text")
                        .HasColumnName("celular");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Direccion")
                        .HasColumnType("text")
                        .HasColumnName("direccion");

                    b.Property<string>("Nombres")
                        .HasColumnType("text")
                        .HasColumnName("nombres");

                    b.Property<Guid>("PersonalId")
                        .HasColumnType("uuid")
                        .HasColumnName("personal_id");

                    b.Property<string>("Telefono")
                        .HasColumnType("text")
                        .HasColumnName("telefono");

                    b.HasKey("Id");

                    b.HasIndex("PersonalId");

                    b.ToTable("contactos_emergencia");
                });

            modelBuilder.Entity("RecursosHumanos.Api.Models.Correspondencia", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CodigoRegistro")
                        .HasColumnType("text")
                        .HasColumnName("codigo_registro");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("FechaHora")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_hora");

                    b.Property<string>("Firma")
                        .HasColumnType("text")
                        .HasColumnName("firma");

                    b.Property<string>("NroOficio")
                        .HasColumnType("text")
                        .HasColumnName("nro_oficio");

                    b.Property<string>("Origen")
                        .HasColumnType("text")
                        .HasColumnName("origen");

                    b.Property<Guid?>("PersonalId")
                        .HasColumnType("uuid")
                        .HasColumnName("personal_id");

                    b.Property<string>("Referencia")
                        .HasColumnType("text")
                        .HasColumnName("referencia");

                    b.Property<string>("Remitente")
                        .HasColumnType("text")
                        .HasColumnName("remitente");

                    b.Property<string>("Seccion")
                        .HasColumnType("text")
                        .HasColumnName("seccion");

                    b.Property<string>("TiempoRespuesta")
                        .HasColumnType("text")
                        .HasColumnName("tiempo_respuesta");

                    b.Property<string>("Tipo")
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.HasIndex("PersonalId");

                    b.ToTable("correspondencia");
                });

            modelBuilder.Entity("RecursosHumanos.Api.Models.Dependiente", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Apellidos")
                        .HasColumnType("text")
                        .HasColumnName("apellidos");

                    b.Property<string>("Celular")
                        .HasColumnType("text")
                        .HasColumnName("celular");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Direccion")
                        .HasColumnType("text")
                        .HasColumnName("direccion");

                    b.Property<string>("Nombres")
                        .HasColumnType("text")
                        .HasColumnName("nombres");

                    b.Property<Guid>("PersonalId")
                        .HasColumnType("uuid")
                        .HasColumnName("personal_id");

                    b.Property<string>("Tipo")
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.HasIndex("PersonalId");

                    b.ToTable("dependientes");
                });

            modelBuilder.Entity("RecursosHumanos.Api.Models.Designacion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AutoridadFirma")
                        .HasColumnType("text")
                        .HasColumnName("autoridad_firma");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly?>("FechaEntrega")
                        .HasColumnType("date")
                        .HasColumnName("fecha_entrega");

                    b.Property<string>("NombreDesignacion")
                        .HasColumnType("text")
                        .HasColumnName("designacion");

                    b.Property<string>("Nro")
                        .HasColumnType("text")
                        .HasColumnName("nro");

                    b.Property<string>("NroFolio")
                        .HasColumnType("text")
                        .HasColumnName("nro_folio");

                    b.Property<string>("NroMemo")
                        .HasColumnType("text")
                        .HasColumnName("nro_memo");

                    b.Property<Guid>("PersonalId")
                        .HasColumnType("uuid")
                        .HasColumnName("personal_id");

                    b.HasKey("Id");

                    b.HasIndex("PersonalId");

                    b.ToTable("designaciones");
                });

            modelBuilder.Entity("RecursosHumanos.Api.Models.Destino", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CargoActual")
                        .HasColumnType("text")
                        .HasColumnName("cargo_actual");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EstadoPersonal")
                        .HasColumnType("text")
                        .HasColumnName("estado_personal");

                    b.Property<DateOnly?>("FechaDestino")
                        .HasColumnType("date")
                        .HasColumnName("fecha_destino");

                    b.Property<string>("MemoNro")
                        .HasColumnType("text")
                        .HasColumnName("memo_nro");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text")
                        .HasColumnName("observaciones");

                    b.Property<Guid>("PersonalId")
                        .HasColumnType("uuid")
                        .HasColumnName("personal_id");

                    b.Property<string>("UnidadActual")
                        .HasColumnType("text")
                        .HasColumnName("unidad_actual");

                    b.Property<string>("UnidadAnterior")
                        .HasColumnType("text")
                        .HasColumnName("unidad_anterior");

                    b.HasKey("Id");

                    b.HasIndex("PersonalId");

                    b.ToTable("destinos");
                });

            modelBuilder.Entity("RecursosHumanos.Api.Models.Disciplinario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AutoridadFirma")
                        .HasColumnType("text")
                        .HasColumnName("autoridad_firma");

                    b.Property<string>("Causal")
                        .HasColumnType("text")
                        .HasColumnName("causal");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly?>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<string>("Nro")
                        .HasColumnType("text")
                        .HasColumnName("nro");

                    b.Property<string>("NroFolio")
                        .HasColumnType("text")
                        .HasColumnName("nro_folio");

                    b.Property<string>("NroMemo")
                        .HasColumnType("text")
                        .HasColumnName("nro_memo");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text")
                        .HasColumnName("observaciones");

                    b.Property<Guid>("PersonalId")
                        .HasColumnType("uuid")
                        .HasColumnName("personal_id");

                    b.HasKey("Id");

                    b.HasIndex("PersonalId");

                    b.ToTable("disciplinario");
                });

            modelBuilder.Entity("RecursosHumanos.Api.Models.Especialidad", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Nombre")
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<string>("Tipo")
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.ToTable("especialidades");
                });

            modelBuilder.Entity("RecursosHumanos.Api.Models.Felicitacion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AutoridadFirma")
                        .HasColumnType("text")
                        .HasColumnName("autoridad_firma");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly?>("FechaEntrega")
                        .HasColumnType("date")
                        .HasColumnName("fecha_entrega");

                    b.Property<string>("Motivo")
                        .HasColumnType("text")
                        .HasColumnName("motivo");

                    b.Property<string>("Nro")
                        .HasColumnType("text")
                        .HasColumnName("nro");

                    b.Property<string>("NroFolio")
                        .HasColumnType("text")
                        .HasColumnName("nro_folio");

                    b.Property<string>("NroMemo")
                        .HasColumnType("text")
                        .HasColumnName("nro_memo");

                    b.Property<Guid>("PersonalId")
                        .HasColumnType("uuid")
                        .HasColumnName("personal_id");

                    b.HasKey("Id");

                    b.HasIndex("PersonalId");

                    b.ToTable("felicitaciones");
                });

            modelBuilder.Entity("RecursosHumanos.Api.Models.Grado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<int>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.HasKey("Id");

                    b.ToTable("grados");
                });

            modelBuilder.Entity("RecursosHumanos.Api.Models.InfoPersonal", b =>
                {
                    b.Property<Guid>("PersonalId")
                        .HasColumnType("uuid")
                        .HasColumnName("personal_id");

                    b.Property<string>("Direccion")
                        .HasColumnType("text")
                        .HasColumnName("direccion");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("EstadoCivil")
                        .HasColumnType("text")
                        .HasColumnName("estado_civil");

                    b.Property<DateOnly?>("FechaIngreso")
                        .HasColumnType("date")
                        .HasColumnName("f_ingreso");

                    b.Property<DateOnly?>("FechaNacimiento")
                        .HasColumnType("date")
                        .HasColumnName("f_nac");

                    b.Property<string>("GrupoSanguineo")
                        .HasColumnType("text")
                        .HasColumnName("grupo_sanguineo");

                    b.Property<string>("Sigep")
                        .HasColumnType("text")
                        .HasColumnName("sigep");

                    b.Property<string>("TelCel")
                        .HasColumnType("text")
                        .HasColumnName("tel_cel");

                    b.Property<string>("TelPart")
                        .HasColumnType("text")
                        .HasColumnName("tel_part");

                    b.Property<string>("Zona")
                        .HasColumnType("text")
                        .HasColumnName("zona");

                    b.HasKey("PersonalId");

                    b.ToTable("info_personal");
                });

            modelBuilder.Entity("RecursosHumanos.Api.Models.Institucion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Nombre")
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<string>("Sigla")
                        .HasColumnType("text")
                        .HasColumnName("sigla");

                    b.Property<string>("Tipo")
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.ToTable("instituciones");
                });

            modelBuilder.Entity("RecursosHumanos.Api.Models.LlamadaAtencion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AutoridadFirma")
                        .HasColumnType("text")
                        .HasColumnName("autoridad_firma");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly?>("FechaEntrega")
                        .HasColumnType("date")
                        .HasColumnName("fecha_entrega");

                    b.Property<string>("Motivo")
                        .HasColumnType("text")
                        .HasColumnName("motivo");

                    b.Property<string>("Nro")
                        .HasColumnType("text")
                        .HasColumnName("nro");

                    b.Property<string>("NroFolio")
                        .HasColumnType("text")
                        .HasColumnName("nro_folio");

                    b.Property<string>("NroMemo")
                        .HasColumnType("text")
                        .HasColumnName("nro_memo");

                    b.Property<Guid>("PersonalId")
                        .HasColumnType("uuid")
                        .HasColumnName("personal_id");

                    b.HasKey("Id");

                    b.HasIndex("PersonalId");

                    b.ToTable("llamadas_atencion");
                });

            modelBuilder.Entity("RecursosHumanos.Api.Models.Pasaporte", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Destino")
                        .HasColumnType("text")
                        .HasColumnName("destino");

                    b.Property<int?>("Dias")
                        .HasColumnType("integer")
                        .HasColumnName("dias");

                    b.Property<DateOnly?>("FechaLlegada")
                        .HasColumnType("date")
                        .HasColumnName("fecha_llegada");

                    b.Property<DateOnly?>("FechaSalida")
                        .HasColumnType("date")
                        .HasColumnName("fecha_salida");

                    b.Property<string>("Motivo")
                        .HasColumnType("text")
                        .HasColumnName("motivo");

                    b.Property<string>("NroFolio")
                        .HasColumnType("text")
                        .HasColumnName("nro_folio");

                    b.Property<string>("NroPasaporte")
                        .HasColumnType("text")
                        .HasColumnName("nro_pasaporte");

                    b.Property<Guid>("PersonalId")
                        .HasColumnType("uuid")
                        .HasColumnName("personal_id");

                    b.HasKey("Id");

                    b.HasIndex("PersonalId");

                    b.ToTable("pasaportes");
                });

            modelBuilder.Entity("RecursosHumanos.Api.Models.Personal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("AlturaCm")
                        .HasColumnType("numeric")
                        .HasColumnName("altura_cm");

                    b.Property<string>("ApEsposo")
                        .HasColumnType("text")
                        .HasColumnName("ap_esposo");

                    b.Property<string>("ApMaterno")
                        .HasColumnType("text")
                        .HasColumnName("ap_materno");

                    b.Property<string>("ApPaterno")
                        .HasColumnType("text")
                        .HasColumnName("ap_paterno");

                    b.Property<string>("Ci")
                        .HasColumnType("text")
                        .HasColumnName("ci");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Escalafon")
                        .HasColumnType("text")
                        .HasColumnName("escalafon");

                    b.Property<string>("Exp")
                        .HasColumnType("text")
                        .HasColumnName("exp");

                    b.Property<string>("FotoUrl")
                        .HasColumnType("text")
                        .HasColumnName("foto_url");

                    b.Property<string>("Genero")
                        .HasColumnType("text")
                        .HasColumnName("genero");

                    b.Property<int?>("GradoId")
                        .HasColumnType("integer")
                        .HasColumnName("grado_id");

                    b.Property<decimal?>("PesoKg")
                        .HasColumnType("numeric")
                        .HasColumnName("peso_kg");

                    b.Property<string>("PrimerNombre")
                        .HasColumnType("text")
                        .HasColumnName("primer_nombre");

                    b.Property<string>("SegundoNombre")
                        .HasColumnType("text")
                        .HasColumnName("segundo_nombre");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("GradoId");

                    b.ToTable("personal");
                });

            modelBuilder.Entity("RecursosHumanos.Api.Models.PersonalEspecialidad", b =>
                {
                    b.Property<Guid>("PersonalId")
                        .HasColumnType("uuid")
                        .HasColumnName("personal_id");

                    b.Property<Guid>("EspecialidadId")
                        .HasColumnType("uuid")
                        .HasColumnName("especialidad_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("PersonalId", "EspecialidadId");

                    b.HasIndex("EspecialidadId");

                    b.ToTable("personal_especialidad");
                });

            modelBuilder.Entity("RecursosHumanos.Api.Models.Reclamacion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly?>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<string>("NroMemorandum")
                        .HasColumnType("text")
                        .HasColumnName("nro_memorandum");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text")
                        .HasColumnName("observaciones");

                    b.Property<Guid>("PersonalId")
                        .HasColumnType("uuid")
                        .HasColumnName("personal_id");

                    b.Property<string>("Tipo")
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.Property<string>("UnidadRepresentada")
                        .HasColumnType("text")
                        .HasColumnName("unidad_representada");

                    b.HasKey("Id");

                    b.HasIndex("PersonalId");

                    b.ToTable("reclamaciones");
                });

            modelBuilder.Entity("RecursosHumanos.Api.Models.RevisionJuridica", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Codigo")
                        .HasColumnType("text")
                        .HasColumnName("codigo");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Destino")
                        .HasColumnType("text")
                        .HasColumnName("destino");

                    b.Property<string>("Entrega")
                        .HasColumnType("text")
                        .HasColumnName("entrega");

                    b.Property<DateOnly?>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<DateTime?>("FechaHora")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_hora");

                    b.Property<string>("Firma")
                        .HasColumnType("text")
                        .HasColumnName("firma");

                    b.Property<string>("Motivo")
                        .HasColumnType("text")
                        .HasColumnName("motivo");

                    b.Property<string>("Origen")
                        .HasColumnType("text")
                        .HasColumnName("origen");

                    b.Property<Guid?>("PersonalId")
                        .HasColumnType("uuid")
                        .HasColumnName("personal_id");

                    b.Property<string>("Recepcion")
                        .HasColumnType("text")
                        .HasColumnName("recepcion");

                    b.Property<string>("Tipo")
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.HasIndex("PersonalId");

                    b.ToTable("revision_juridica");
                });

            modelBuilder.Entity("RecursosHumanos.Api.Models.Rol", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("roles");
                });

            modelBuilder.Entity("RecursosHumanos.Api.Models.Situacion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Causal")
                        .HasColumnType("text")
                        .HasColumnName("causal");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly?>("FechaInicio")
                        .HasColumnType("date")
                        .HasColumnName("fecha_inicio");

                    b.Property<DateOnly?>("FechaRetorno")
                        .HasColumnType("date")
                        .HasColumnName("fecha_retorno");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text")
                        .HasColumnName("observaciones");

                    b.Property<Guid>("PersonalId")
                        .HasColumnType("uuid")
                        .HasColumnName("personal_id");

                    b.Property<string>("SituacionActual")
                        .HasColumnType("text")
                        .HasColumnName("situacion_actual");

                    b.Property<string>("Tipo")
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.HasIndex("PersonalId");

                    b.ToTable("situaciones");
                });

            modelBuilder.Entity("RecursosHumanos.Api.Models.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Username")
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.ToTable("usuarios");
                });

            modelBuilder.Entity("RecursosHumanos.Api.Models.UsuarioRol", b =>
                {
                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<Guid>("RolId")
                        .HasColumnType("uuid")
                        .HasColumnName("rol_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("UsuarioId", "RolId");

                    b.HasIndex("RolId");

                    b.ToTable("usuario_rol");
                });

            modelBuilder.Entity("RecursosHumanos.Api.Models.Vacacion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AutoridadFirma")
                        .HasColumnType("text")
                        .HasColumnName("autoridad_firma");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly?>("Desde")
                        .HasColumnType("date")
                        .HasColumnName("desde");

                    b.Property<int?>("Dias")
                        .HasColumnType("integer")
                        .HasColumnName("dias");

                    b.Property<DateOnly?>("Hasta")
                        .HasColumnType("date")
                        .HasColumnName("hasta");

                    b.Property<string>("Nro")
                        .HasColumnType("text")
                        .HasColumnName("nro");

                    b.Property<string>("NroMemo")
                        .HasColumnType("text")
                        .HasColumnName("nro_memo");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text")
                        .HasColumnName("observaciones");

                    b.Property<Guid>("PersonalId")
                        .HasColumnType("uuid")
                        .HasColumnName("personal_id");

                    b.HasKey("Id");

                    b.HasIndex("PersonalId");

                    b.ToTable("vacaciones");
                });

            modelBuilder.Entity("RecursosHumanos.Api.Models.ArchivoRel", b =>
                {
                    b.HasOne("RecursosHumanos.Api.Models.Archivo", "Archivo")
                        .WithMany("ArchivosRel")
                        .HasForeignKey("ArchivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Archivo");
                });

            modelBuilder.Entity("RecursosHumanos.Api.Models.Asignacion", b =>
                {
                    b.HasOne("RecursosHumanos.Api.Models.Institucion", "Institucion")
                        .WithMany("Asignaciones")
                        .HasForeignKey("InstitucionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecursosHumanos.Api.Models.Personal", "Personal")
                        .WithMany("Asignaciones")
                        .HasForeignKey("PersonalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Institucion");

                    b.Navigation("Personal");
                });

            modelBuilder.Entity("RecursosHumanos.Api.Models.AuditLog", b =>
                {
                    b.HasOne("RecursosHumanos.Api.Models.Usuario", "Actor")
                        .WithMany("AuditLogs")
                        .HasForeignKey("ActorId");

                    b.Navigation("Actor");
                });

            modelBuilder.Entity("RecursosHumanos.Api.Models.Baja", b =>
                {
                    b.HasOne("RecursosHumanos.Api.Models.Personal", "Personal")
                        .WithMany("Bajas")
                        .HasForeignKey("PersonalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personal");
                });

            modelBuilder.Entity("RecursosHumanos.Api.Models.BajaMedica", b =>
                {
                    b.HasOne("RecursosHumanos.Api.Models.Personal", "Personal")
                        .WithMany("BajasMedicas")
                        .HasForeignKey("PersonalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personal");
                });

            modelBuilder.Entity("RecursosHumanos.Api.Models.Comision", b =>
                {
                    b.HasOne("RecursosHumanos.Api.Models.Personal", "Personal")
                        .WithMany("Comisiones")
                        .HasForeignKey("PersonalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personal");
                });

            modelBuilder.Entity("RecursosHumanos.Api.Models.ContactoEmergencia", b =>
                {
                    b.HasOne("RecursosHumanos.Api.Models.Personal", "Personal")
                        .WithMany("ContactosEmergencia")
                        .HasForeignKey("PersonalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personal");
                });

            modelBuilder.Entity("RecursosHumanos.Api.Models.Correspondencia", b =>
                {
                    b.HasOne("RecursosHumanos.Api.Models.Personal", "Personal")
                        .WithMany("Correspondencias")
                        .HasForeignKey("PersonalId");

                    b.Navigation("Personal");
                });

            modelBuilder.Entity("RecursosHumanos.Api.Models.Dependiente", b =>
                {
                    b.HasOne("RecursosHumanos.Api.Models.Personal", "Personal")
                        .WithMany("Dependientes")
                        .HasForeignKey("PersonalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personal");
                });

            modelBuilder.Entity("RecursosHumanos.Api.Models.Designacion", b =>
                {
                    b.HasOne("RecursosHumanos.Api.Models.Personal", "Personal")
                        .WithMany("Designaciones")
                        .HasForeignKey("PersonalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personal");
                });

            modelBuilder.Entity("RecursosHumanos.Api.Models.Destino", b =>
                {
                    b.HasOne("RecursosHumanos.Api.Models.Personal", "Personal")
                        .WithMany("Destinos")
                        .HasForeignKey("PersonalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personal");
                });

            modelBuilder.Entity("RecursosHumanos.Api.Models.Disciplinario", b =>
                {
                    b.HasOne("RecursosHumanos.Api.Models.Personal", "Personal")
                        .WithMany("Disciplinarios")
                        .HasForeignKey("PersonalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personal");
                });

            modelBuilder.Entity("RecursosHumanos.Api.Models.Felicitacion", b =>
                {
                    b.HasOne("RecursosHumanos.Api.Models.Personal", "Personal")
                        .WithMany("Felicitaciones")
                        .HasForeignKey("PersonalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personal");
                });

            modelBuilder.Entity("RecursosHumanos.Api.Models.InfoPersonal", b =>
                {
                    b.HasOne("RecursosHumanos.Api.Models.Personal", "Personal")
                        .WithOne("InfoPersonal")
                        .HasForeignKey("RecursosHumanos.Api.Models.InfoPersonal", "PersonalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personal");
                });

            modelBuilder.Entity("RecursosHumanos.Api.Models.LlamadaAtencion", b =>
                {
                    b.HasOne("RecursosHumanos.Api.Models.Personal", "Personal")
                        .WithMany("LlamadasAtencion")
                        .HasForeignKey("PersonalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personal");
                });

            modelBuilder.Entity("RecursosHumanos.Api.Models.Pasaporte", b =>
                {
                    b.HasOne("RecursosHumanos.Api.Models.Personal", "Personal")
                        .WithMany("Pasaportes")
                        .HasForeignKey("PersonalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personal");
                });

            modelBuilder.Entity("RecursosHumanos.Api.Models.Personal", b =>
                {
                    b.HasOne("RecursosHumanos.Api.Models.Grado", "Grado")
                        .WithMany("Personal")
                        .HasForeignKey("GradoId");

                    b.Navigation("Grado");
                });

            modelBuilder.Entity("RecursosHumanos.Api.Models.PersonalEspecialidad", b =>
                {
                    b.HasOne("RecursosHumanos.Api.Models.Especialidad", "Especialidad")
                        .WithMany("PersonalEspecialidades")
                        .HasForeignKey("EspecialidadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecursosHumanos.Api.Models.Personal", "Personal")
                        .WithMany("PersonalEspecialidades")
                        .HasForeignKey("PersonalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Especialidad");

                    b.Navigation("Personal");
                });

            modelBuilder.Entity("RecursosHumanos.Api.Models.Reclamacion", b =>
                {
                    b.HasOne("RecursosHumanos.Api.Models.Personal", "Personal")
                        .WithMany("Reclamaciones")
                        .HasForeignKey("PersonalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personal");
                });

            modelBuilder.Entity("RecursosHumanos.Api.Models.RevisionJuridica", b =>
                {
                    b.HasOne("RecursosHumanos.Api.Models.Personal", "Personal")
                        .WithMany("RevisionesJuridicas")
                        .HasForeignKey("PersonalId");

                    b.Navigation("Personal");
                });

            modelBuilder.Entity("RecursosHumanos.Api.Models.Situacion", b =>
                {
                    b.HasOne("RecursosHumanos.Api.Models.Personal", "Personal")
                        .WithMany("Situaciones")
                        .HasForeignKey("PersonalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personal");
                });

            modelBuilder.Entity("RecursosHumanos.Api.Models.UsuarioRol", b =>
                {
                    b.HasOne("RecursosHumanos.Api.Models.Rol", "Rol")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecursosHumanos.Api.Models.Usuario", "Usuario")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("RecursosHumanos.Api.Models.Vacacion", b =>
                {
                    b.HasOne("RecursosHumanos.Api.Models.Personal", "Personal")
                        .WithMany("Vacaciones")
                        .HasForeignKey("PersonalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personal");
                });

            modelBuilder.Entity("RecursosHumanos.Api.Models.Archivo", b =>
                {
                    b.Navigation("ArchivosRel");
                });

            modelBuilder.Entity("RecursosHumanos.Api.Models.Especialidad", b =>
                {
                    b.Navigation("PersonalEspecialidades");
                });

            modelBuilder.Entity("RecursosHumanos.Api.Models.Grado", b =>
                {
                    b.Navigation("Personal");
                });

            modelBuilder.Entity("RecursosHumanos.Api.Models.Institucion", b =>
                {
                    b.Navigation("Asignaciones");
                });

            modelBuilder.Entity("RecursosHumanos.Api.Models.Personal", b =>
                {
                    b.Navigation("Asignaciones");

                    b.Navigation("Bajas");

                    b.Navigation("BajasMedicas");

                    b.Navigation("Comisiones");

                    b.Navigation("ContactosEmergencia");

                    b.Navigation("Correspondencias");

                    b.Navigation("Dependientes");

                    b.Navigation("Designaciones");

                    b.Navigation("Destinos");

                    b.Navigation("Disciplinarios");

                    b.Navigation("Felicitaciones");

                    b.Navigation("InfoPersonal");

                    b.Navigation("LlamadasAtencion");

                    b.Navigation("Pasaportes");

                    b.Navigation("PersonalEspecialidades");

                    b.Navigation("Reclamaciones");

                    b.Navigation("RevisionesJuridicas");

                    b.Navigation("Situaciones");

                    b.Navigation("Vacaciones");
                });

            modelBuilder.Entity("RecursosHumanos.Api.Models.Rol", b =>
                {
                    b.Navigation("UsuarioRoles");
                });

            modelBuilder.Entity("RecursosHumanos.Api.Models.Usuario", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("UsuarioRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
